apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kyverno
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kyverno
  ingress:
    - fromEntities:
      - "kube-apiserver"
  egress:
    - toEntities:
      - "kube-apiserver"
