---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-private
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: contour-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    path: configs/contour-private
    repoURL: https://github.com/alleaffengaffen/banana.git
    targetRevision: HEAD
