apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kured
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    chart: kured
    repoURL: https://kubereboot.github.io/charts/
    targetRevision: 4.2.x
    helm:
      version: v3
      values: |-
        configuration:
          rebootDays: [mo, tu,we,th,fr]
          endTime: "6am"            
          startTime: "10pm"
          drainTimeout: "1h"              
          timeZone: "Europe/Zurich"       
          annotateNodes: true

        resources:
          limits:
            cpu: 5m
            memory: 48Mi
          requests:
            cpu: 1m
            memory: 16Mi
