apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-production
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: banane@alleaffengaffen.ch
   privateKeySecretRef:
     name: letsencrypt-production
   solvers:
    - selector: {}
      dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
