rollOutCiliumPods: true
priorityClassName: "system-node-critical"
annotateK8sNode: true
policyEnforcementMode: "default" # will be activated later on
operator:
  replicas: 1
  rollOutPods: true
containerRuntime:
  integration: containerd
  socketPath: /var/run/containerd/containerd.sock
l7Proxy: false # not possible with encryption
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
# host-firewall will be activated later on
kubeProxyReplacement: "strict"
k8sServiceHost: "api.alleaffengaffen.ch"
k8sServicePort: "6443"
