apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oidc
  namespace: kube-system
spec:
  encryptedData:
    clientSecret: AgA4zcVGEjaUc4+kghbgkSJNq311zgVq54Eakf/TLXeKviL1j/6QSLtvq1FYHiItyNKgO9OuJLzRL5dTUoluNmPX9B4vTlF+zpXUEupWmYLioymKSQY2utGz7E1+qkuPAhT7deRc7ay5N9ie38J+bhCM5oE61D7yeg0WcDjXTNhYaRA40LGikBDRk7fE4omntp8eyoGBkOa9Jf/a2wL0JxO2WBpT3JIpq4IBwykbMtXpg0oLdcoYofyNDXy2e+KyjkcEd5M/+4B2mjCZdLErbF31JC+ctqwq1cPy6/ayexb31akaUI/WcitG8VCb/imsZkjUT3sFDAh8GpH2hbdtX9E4uCtgXjOGr6ex7/B/82UUAq4Df/ZVn+/JCwjdU3Hzlao9tyH9KCVluhONILQihwvShAoBpsGdrSjJXvGy7gf5uoo94LFUb1HV/HiTVmzG/2+m8r6LeUk4/C6ADiU2iU67nDICggom03Cwgh1VjDVMTYr/wq5CoWbRES6URMQvoJpbiE0vIvtJOEvOe1fL52E49MH3wv2C1WvcMW8QC6GlF1IWq0+bRTCY4l8gE/RAMJlX6DayUgoMrNO2IJ2fSZtzZ6g6UEozclfsvZoSuO/0+Meex+8HXwET8uCoy+9P75zfuif+S8heKT3ziCOxDSCA4IfTOr0IlMPknTVvrvOnlnTdLsRtanIKrhX2jvr8B0n4h1DLXLi8BTWTqN55AgRnNW/Byb/SvV+FozXo6KSNNfu/Jo4qWdib
  template:
    metadata:
      creationTimestamp: null
      name: github-oidc
      namespace: kube-system

